### ISSUE TITLE
PGID and PUID doesn't work

### ISSUE THREAD

**Issue by Itsmmai** [linuxserver/docker-nzbget#50] opened 2018-03-08 15:10 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

##  Thanks, team linuxserver.io

Hi,

When I use the PGID and PUID env variables in my docker it doesn't seem to work. It keeps running in GID 100 UID 1. Please help.

Kind regards,
Abel

**Comment by j0nnymoe** [comment] 2018-03-08 15:28
docker create/run command + host os info please

**Comment by Itsmmai** [comment] 2018-03-08 16:14
I created and start my docker with docker for synology. DSM 6.1 and the linux server.io/sickrage docker does work with the same settings.

**Comment by sparklyballs** [comment] 2018-03-08 16:15
a screen shot of your settings will do in lieu of a run command

**Comment by Itsmmai** [comment] 2018-03-08 16:20
<img width="1266" alt="schermafbeelding 2018-03-08 om 17 18 39" src="https://user-images.githubusercontent.com/24639986/37162202-f15869d2-22f4-11e8-8640-029941ca0157.png">

**Comment by sparklyballs** [comment] 2018-03-08 16:28
hit the command line and run the following

`docker exec -it nzbget bash`

if you  changed the container name substitute that for nzbget above

and then run 

`id abc`

**Comment by Itsmmai** [comment] 2018-03-08 16:36
root@nzbget:/$ id abc                                                                                    
uid=0(root) gid=100(abc) groups=100(abc),0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(flop
py),20(dialout),26(tape),27(video)

**Comment by sparklyballs** [comment] 2018-03-08 16:37
what is the /home  setting ?

**Comment by sparklyballs** [comment] 2018-03-08 16:41
from the command line also can you run 

`docker images`

and 

`docker ps -a`

**Comment by sparklyballs** [comment] 2018-03-08 16:43
https://pastebin.com/CjvRCSaG

as you can see the image does respect GID and PID

**Comment by Itsmmai** [comment] 2018-03-08 18:00
root@nzbget:/$ ps -a                                                                                     
PID   USER     TIME   COMMAND                                                                            
    1 root       0:00 s6-svscan -t0 /var/run/s6/services                                                 
   34 root       0:00 s6-supervise s6-fdholderd                                                          
  202 root       0:00 s6-supervise nzbget                                                                
  205 root       4:51 /app/nzbget/nzbget -s -c /config/nzbget.conf -o OutputMode=log                     
 5008 root       0:00 /bin/bash                                                                          
 6859 root       0:00 ps -a                                                                              
root@nzbget:/$    

and /home = /root

**Comment by aptalca** [comment] 2018-03-08 18:23
do `docker ps -a` on the host, not inside the container

**Comment by Itsmmai** [comment] 2018-03-08 18:35
admin@NAS:/volume1/Downloads/completed/tv$ sudo docker ps -a
CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS              PORTS                                            NAMES
e52d31def858        linuxserver/sickrage:latest   "/init"                  3 hours ago         Up 3 hours          0.0.0.0:8081->8081/tcp                           SickRage
c341b9d58da4        linuxserver/nzbget:latest     "/init"                  20 hours ago        Up 3 hours          0.0.0.0:6789->6789/tcp, 0.0.0.0:6791->6791/tcp   nzbget
c10980ce82a2        oznu/homebridge:debian        "/init"                  31 hours ago        Up 7 hours                                                           homebridge

**Comment by mrsparx** [comment] 2018-04-01 22:37
I have the same issue with linuxserver-syncthing. I tested build 100 where both PUID and PGID seems to work correctly. In build 105 only PUID is correct and in latest 109 PUID never works and PGID varies from working or showing 911. Sorry if this is the wrong place to post. Also running under synology 6.1.

**Comment by thelamer** [comment] 2019-02-22 20:11
The docker interface for creating containers in Synology is a bit of a shitshow IMPO. If you are having problems passing Env variables to create a container I recommend performing your container creation with another web based tool like Portainer or Taisun. 
https://www.portainer.io/
https://github.com/Taisun-Docker/taisun/wiki/Synology

I am closing this issue as I am not able to reproduce this locally even on a Synology, though I do not use their WebUI for container management.

**Closed by thelamer** 2019-02-22 20:11 UTC
