### ISSUE TITLE
hardcoded path inside download dir

### ISSUE THREAD

**Issue by Benni-chan** [linuxserver/docker-nzbget#3] opened 2015-09-01 11:41 UTC
why are you forcing some path to the download dir?

    sed -i -e "s#\(LogFile=\).*#\1$\{MainDir\}/nzbget.log#g" /config/nzbget.conf

I like to have my nzbget log flies inside the config folder and not filling up the download folder.
same thing with the nzbget.lock. you have a script in the startup routine, which deletes the nzbget.lock file in /download. since this is also a variable in the nzbget settings, a user could change this.

**Comment by lonix** [comment] 2015-10-06 07:21
Took me 36 days to get to you, sorry about that. The reason we hardcode the path to the logfile is due to the fact we are "tail" ing that file to display as a log, seeming as we cant really get nzbget to run in fg mode anymore. But your comments are welcome, and i will see what we can do about this.

**Comment by billimek** [comment] 2015-10-12 16:54
I've got the same concern about hardcoding the location of the lock and log file.  I prefer to keep them in /config.

**Comment by lonix** [comment] 2015-10-13 11:05
Ill lok into this.

**Comment by Shmixx** [comment] 2015-12-28 05:19
Adding in a concern here from me as well - commented on the Docker Hub page too in case it gets seen quicker. This is really going to botch up my Downloads directory since I choose to keep 30 days of rotating logs. Also not a good place for the lock file.

**Comment by 1activegeek** [comment] 2016-01-21 15:22
So I'm not a snazzy coder at all, but any reason why this is done this way? I use many of the other LinuxServer.io containers that have logs and PIDs that are not Hardcoded into these paths.

**Comment by neersighted** [comment] 2016-02-27 08:03
Doesn't nzbget log straight to stdout? If you follow the log the docker log grows to stupid sizes because of DETAIL level logging...

**Comment by neersighted** [comment] 2016-02-29 17:32
In addition, it seems like if a path has to be hardcoded /config would be a better path...

**Comment by 1activegeek** [comment] 2016-02-29 18:13
Agreed - I personally would love to see a logging path that can be mapped to a mapped volume - I commonly map a logging directory to my docker containers so I can aggregate all logs from all apps/containers to a single location.

**Comment by JTarasovic** [comment] 2016-04-30 14:50
The default directory layout looks something like this. 

```
<root> (AppDir)
    - /downloads (MainDir)
        - /completed (DestDir)
        - /intermediate (InterDir)
        - /nzb (NzbDir)
        - /queue (QueueDir)
        - /tmp (TmpDir)
        - nzbget.log (LogFile)
        - nzbget.lock (LockFile)
    - /scripts (ScriptsDir)
    - /webui (WebDir)
        - nzbget.conf.template
``` 

Inside the container, `${MainDir}` is what is being mapped as the /downloads volume. It's a bit weird that it's called "downloads" since things actually should go `intermediate -> completed` but there should still only be those 2 files at the root of that dir. I think the above referenced PR, #11, should allow the container to not require a fixed location for the log and lock file though.  


config file defaults reference:
https://github.com/nzbget/nzbget/blob/develop/nzbget.conf
https://github.com/nzbget/nzbget/blob/develop/linux/build-nzbget#L341

**Comment by lonix** [comment] 2016-05-01 11:57
#11 should close this.

**Closed by lonix** 2016-05-01 11:57 UTC
Labels: enhancement

**Comment by 1activegeek** [comment] 2016-05-22 19:51
So it seems this solves the issue with the lock file, but it doesn't look to resolve the logging issue. Logs are still reset anytime the container is reset. It survives reloads of the daemon, but doesn't survive restart of container.

**Comment by JTarasovic** [comment] 2016-05-26 06:03
I don't think that has anything to do with the container. /downloads should be mapped to whatever volume that you pass in and the log (like everything in that dir) should survive a shutdown.

In the NZBGet settings, under logs, make sure `append` is selected instead of `reset`. A quick grep of the conf should confirm or deny.

It also may be related to nzbget/nzbget@18d89435e4 which looks like it fixed a problem where the logs were getting deleted inappropriately.

**Comment by 1activegeek** [comment] 2016-05-26 12:38
@JTarasovic yes the log file is surviving. That's not the issue. It's the setting for where the log file is placed that is being reset as it doesn't survive a container restart. The issue is that I don't want a pile of logs loaded in my downloads directory. I specify the logs to be placed in another mapped location. Unfortunately it only lasts until a container restart.

**Comment by JTarasovic** [comment] 2016-05-26 12:58
Have you blown away the image and pulled the most recent?

`docker rmi -f linuxserver/docker-nzbget && docker create ...`

**Comment by 1activegeek** [comment] 2016-05-26 13:26
I pulled the most recent, but I hadn't blown the image away. I'm a bit OCD and when I blow away my images, I have to re-create the containers too otherwise they show the image as being the ID vs the friendly name for some reason. Perhaps I will try pulling fresh image and fresh container on a test system to see if it functions as expected.
