### ISSUE TITLE
Javascript error after image upgrade

### ISSUE THREAD

**Issue by Dagur** [linuxserver/docker-nzbget#124] opened 2021-02-21 22:06 UTC
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Pulled a new image and now the UI is broken

------------------------------

## Expected Behavior
Successful upgrade

## Current Behavior

```
Error in http://192.168.88.56:6789/combined.js?lib/jquery.min.js+lib/bootstrap.min.js+lib/raphael.min.js+lib/elycharts.min.js+fasttable.js+index.js+util.js+downloads.js+edit.js+status.js+messages.js+history.js+upload.js+config.js+feed.js (line 8727)
Uncaught TypeError: Cannot read property 'length' of undefined
```

## Steps to Reproduce

1. Stop docker image
2. rm docker image
3. dockre pull linuxserver/nzbget
4. run docker image

## Environment
**OS:** raspi
**CPU architecture:** arm64 (armhf)
**How docker service was installed:**

Distro repo

## Command used to create docker container (run/create/compose/screenshot)

```
$ docker pull linuxserver/nzbget

$ docker run -d --name="nzbget" --restart=always -v /home/sabuser/nzbget:/config -v /home/sabuser/downloads:/downloads -v /etc/localtime:/etc/localtime:ro -p 6789:6789 -e PUID=1003 -e PGID=1003  linuxserver/nzbget
```

## Docker logs

n/a

Sonarr can't communicate with nzbget anymore either:

```
Unable to communicate with nzbget. Unable to connect to NzbGet. Error getting response stream (ReadDoneAsync2): ReceiveFailure: 'http://192.168.88.56:6789/jsonrpc'
```

**Comment by Dagur** [comment] 2021-02-22 22:03
I'm just guessing, but it might have something to do with this https://github.com/nzbget/nzbget/issues/736

I pulled an older image and everything works fine now.

**Comment by U8208306949** [comment] 2021-03-03 14:37
I too am receiving something similar since docker update on rPi  (armhf). Docker images till v21.0-ls70 and before working fine, later images throw following error:

_Error in http://192.168.99.103:6789/combined.js?lib/jquery.min.js+lib/bootstrap.min.js+lib/raphael.min.js+lib/elycharts.min.js+fasttable.js+index.js+util.js+downloads.js+edit.js+status.js+messages.js+history.js+upload.js+config.js+feed.js (line 3488)

Uncaught TypeError: Cannot read property 'length' of undefined_

**Comment by tobbenb** [comment] 2021-03-03 19:00
Might help if you supply full container logs. We do ask for it for a reason.

**Comment by Dagur** [comment] 2021-03-03 19:02
It was empty for me

**Comment by tobbenb** [comment] 2021-03-03 19:07
docker logs containername doesn't provide any output? Then your container shouldn't be running.

**Comment by Dagur** [comment] 2021-03-03 20:24
There were no errors. I could see the startup info

**Comment by tobbenb** [comment] 2021-03-03 21:05
This is the last time I ask for the container log. If you can't supply it, I'm closing the issue.

**Comment by Dagur** [comment] 2021-03-03 21:06
I'll do it for you

**Comment by Roxedus** [comment] 2021-03-03 21:09
The reason we ask, is because what you might brush of as nothing, might be the key to solving this.

**Comment by Dagur** [comment] 2021-03-03 21:17
> [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
> [s6-init] ensuring user provided files have correct perms...exited 0.
> [fix-attrs.d] applying ownership & permissions fixes...
> [fix-attrs.d] done.
> [cont-init.d] executing container initialization scripts...
> [cont-init.d] 01-envfile: executing... 
> [cont-init.d] 01-envfile: exited 0.
> [cont-init.d] 10-adduser: executing... 
> 
> -------------------------------------
>           _         ()
>          | |  ___   _    __
>          | | / __| | |  /  \ 
>          | | \__ \ | | | () |
>          |_| |___/ |_|  \__/
> 
> 
> Brought to you by linuxserver.io
> -------------------------------------
> 
> To support the app dev(s) visit:
> NZBGet: https://nzbget.net/donate
> 
> To support LSIO projects visit:
> https://www.linuxserver.io/donate/
> -------------------------------------
> GID/UID
> -------------------------------------
> 
> User uid:    1003
> User gid:    1003
> -------------------------------------
> 
> [cont-init.d] 10-adduser: exited 0.
> [cont-init.d] 30-config: executing... 
> [cont-init.d] 30-config: exited 0.
> [cont-init.d] 99-custom-files: executing... 
> [custom-init] no custom files found exiting...
> [cont-init.d] 99-custom-files: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> [INFO] nzbget 21.0 server-mode
> [INFO] nzbget 21.0 server-mode
> [INFO] nzbget 21.0 server-mode
> [INFO] nzbget 21.0 server-mode
> [INFO] nzbget 21.0 server-mode
> 

Each time I try to access the web view I get 

> Communication error!
> Invalid Status: 502

in the browser and a new 

> [INFO] nzbget 21.0 server-mode

line is added to the log

**Comment by Dagur** [comment] 2021-03-03 21:19
{
"version" : "1.1",
"error" : {
"name" : "JSONRPCError",
"code" : 1,
"message" : "Invalid procedure"
}
}

if I try to access /jsonrpc

and

> [INFO] nzbget 21.0 server-mode

line is added to the log

**Comment by Roxedus** [comment] 2021-03-03 21:29
Just to cover our bases, does `date` in the container result in a reasonable time?

**Comment by Dagur** [comment] 2021-03-04 19:05
> dagur@raspberrypi:~ $ date
> Thu Mar  4 19:04:23 GMT 2021
> dagur@raspberrypi:~ $ docker exec -it nzbget bash
> root@37ef8f94bfa4:/# date
> Thu Mar  4 19:04:31 GMT 2021
>

**Comment by H34dl3ss** [comment] 2021-03-10 21:40
I see the same issue with the update I pulled today.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

brought to you by linuxserver.io
-------------------------------------
To support the app dev(s) visit:
NZBGet: https://nzbget.net/donate

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    100
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[INFO] nzbget 21.0 server-mode
```

When trying to access the webinterface I get:
```
Communication error!
Cannot establish connection to NZBGet.
```
With regard to the "bases":
$ date
Mi 10. Mär 22:33:36 CET 2021

Using Firefox 86

On my other PC, the webinterface switched to a more verbose failure message after some time.
If I manage to reproduce it, I will come back and add it to this post.

If I can assist with other information, don't hesitate to ask.

**Comment by Roxedus** [comment] 2021-04-12 20:07
#130 should fix this. Let me know if it didn't

**Closed by Roxedus** 2021-04-12 20:07 UTC
Labels: no-issue-activity
